defmodule Mix.Tasks.GettextTs.Codegen do
  @moduledoc """
  Generates typed TypeScript catalogs from the Gettext PO tree.

  Output (under `:output_path`):

    * `catalog/<locale>.ts` — one file per locale, nested domain → msgid →
      msgstr. The frontend loads only the locale it needs.
    * `index.ts` — `locales`, `domains`, `Locale`/`Domain`/`TranslationKey`
      types, `loadCatalog(locale)` (dynamic import), and `createT` with
      `%{var}` interpolation and an overrides layer for runtime-edited
      translations.
    * `react.tsx` — provider + `useT(domain?)` hook (unless `react: false`).
      The provider takes an optional `initialCatalog` so a server-rendered
      route tree is already translated before hydration.

  Files are only written when content changed, so `--check` in CI is cheap.
  """
  use Mix.Task

  @shortdoc "Generate TypeScript catalogs from PO files"

  alias GettextTs.{Catalog, Config}

  @impl Mix.Task
  def run(args) do
    {opts, _, _} = OptionParser.parse(args, switches: [check: :boolean])

    data = Catalog.read()
    pot = Catalog.pot_index()
    out = Path.expand(Config.output_path(), File.cwd!())
    File.mkdir_p!(Path.join(out, "catalog"))

    files =
      for {locale, by_domain} <- data, into: %{} do
        {Path.join([out, "catalog", "#{locale}.ts"]), locale_ts(locale, by_domain)}
      end

    files = Map.put(files, Path.join(out, "index.ts"), index_ts(data, pot))

    files =
      if Config.react?(),
        do: Map.put(files, Path.join(out, "react.tsx"), react_tsx()),
        else: files

    changed =
      for {path, content} <- files, File.read(path) != {:ok, content} do
        unless opts[:check], do: File.write!(path, content)
        Path.relative_to_cwd(path)
      end

    cond do
      changed == [] ->
        :ok

      opts[:check] ->
        Mix.raise("gettext_ts.codegen --check: stale files: #{Enum.join(changed, ", ")}")

      true ->
        Mix.shell().info(
          "gettext_ts: wrote #{length(changed)} file(s) under #{Config.output_path()}"
        )
    end
  end

  defp locale_ts(locale, by_domain) do
    domains =
      by_domain
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map_join(",\n", fn {domain, entries} ->
        lines =
          entries
          |> Enum.sort_by(&elem(&1, 0))
          |> Enum.map_join(",\n", fn {id, str} -> "    #{ts_str(id)}: #{ts_str(str)}" end)

        "  #{ts_str(domain)}: {\n#{lines}\n  }"
      end)

    """
    // AUTO-GENERATED by mix gettext_ts.codegen — DO NOT EDIT
    // Locale: #{locale}. Source: PO files under priv/gettext.
    const catalog = {
    #{domains}
    } as const;

    export default catalog;
    """
  end

  defp index_ts(data, pot) do
    locales = data |> Map.keys() |> Enum.sort()
    domains = pot |> Map.keys() |> Enum.sort()
    default_domain = Config.default_domain()

    key_union =
      pot
      |> Enum.flat_map(fn {_d, ids} -> ids end)
      |> Enum.uniq()
      |> Enum.sort()
      |> case do
        [] -> "never"
        ids -> Enum.map_join(ids, "\n  | ", &ts_str/1)
      end

    """
    // AUTO-GENERATED by mix gettext_ts.codegen — DO NOT EDIT
    export const locales = [#{Enum.map_join(locales, ", ", &ts_str/1)}] as const;
    export const domains = [#{Enum.map_join(domains, ", ", &ts_str/1)}] as const;
    export type Locale = (typeof locales)[number];
    export type Domain = (typeof domains)[number];
    export type TranslationKey =
      | #{key_union};

    export type DomainCatalog = Record<string, string>;
    export type LocaleCatalog = Record<string, DomainCatalog>;
    /** Runtime-edited translations layered over the compiled catalog. */
    export type Overrides = Partial<Record<string, DomainCatalog>>;

    export function loadCatalog(locale: string): Promise<LocaleCatalog> {
      switch (locale) {
    #{Enum.map_join(locales, "\n", fn l -> "    case #{ts_str(l)}:\n      return import(#{ts_str("./catalog/" <> l)}).then((m) => m.default as LocaleCatalog);" end)}
        default:
          return Promise.resolve({});
      }
    }

    export type TFunction = (
      key: TranslationKey | (string & {}),
      vars?: Record<string, string | number>
    ) => string;

    function interpolate(s: string, vars?: Record<string, string | number>): string {
      if (!vars) return s;
      let out = s;
      for (const [k, v] of Object.entries(vars)) out = out.replaceAll(`%{${k}}`, String(v));
      return out;
    }

    /**
     * Translation function for one domain. Lookup order: overrides →
     * compiled catalog → the key itself (source-language passthrough, so
     * new strings render before codegen ran).
     */
    export function createT(
      catalog: LocaleCatalog | null,
      domain: string = #{ts_str(default_domain)},
      overrides?: Overrides
    ): TFunction {
      return (key, vars) =>
        interpolate(
          overrides?.[domain]?.[key] ?? catalog?.[domain]?.[key] ?? key,
          vars
        );
    }
    """
  end

  defp react_tsx do
    default_domain = Config.default_domain()

    """
    // AUTO-GENERATED by mix gettext_ts.codegen — DO NOT EDIT
    "use client";

    import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
    import { createT, loadCatalog, type LocaleCatalog, type Overrides, type TFunction } from "./index";

    const Ctx = createContext<{ catalog: LocaleCatalog | null; overrides?: Overrides }>({ catalog: null });

    /** Locale-aware translation hook. Renders source-language keys until a catalog is present. */
    export function useT(domain: string = #{inspect(default_domain)}): TFunction {
      const { catalog, overrides } = useContext(Ctx);
      return useMemo(() => createT(catalog, domain, overrides), [catalog, domain, overrides]);
    }

    /**
     * Loads the locale's catalog lazily. `overrides` carries runtime-edited
     * translations (e.g. admin-changed copy fetched from the backend) and is
     * layered over the compiled catalog.
     *
     * `initialCatalog` seeds the FIRST render, server included. Without it the
     * catalog is null until the effect resolves, so a server-rendered page in a
     * non-source locale ships source-language HTML and swaps after hydration —
     * invisible to crawlers and a visible flash to everyone else. Import the
     * locale's catalog statically and pass it here for a per-locale route tree;
     * the lazy load still runs and refreshes the state afterwards.
     */
    export function I18nProvider({ locale, overrides, initialCatalog, children }: {
      locale: string; overrides?: Overrides; initialCatalog?: LocaleCatalog; children: ReactNode;
    }) {
      const [catalog, setCatalog] = useState<LocaleCatalog | null>(initialCatalog ?? null);

      useEffect(() => {
        let cancelled = false;
        loadCatalog(locale).then((c) => { if (!cancelled) setCatalog(c); });
        return () => { cancelled = true; };
      }, [locale]);

      const value = useMemo(() => ({ catalog, overrides }), [catalog, overrides]);
      return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
    }
    """
  end

  defp ts_str(s) do
    escaped =
      s
      |> String.replace("\\", "\\\\")
      |> String.replace("\"", "\\\"")
      |> String.replace("\n", "\\n")

    "\"#{escaped}\""
  end
end
