defmodule Mix.Tasks.GettextTs.Codegen do
  @moduledoc """
  Generates typed TypeScript catalogs from the Gettext PO tree.

  Output (under `:output_path`):

    * `catalog/<locale>/<domain>.ts` — one file per locale AND domain. The
      unit of loading is the domain, not the locale: an application whose
      admin copy outweighs its public copy would otherwise ship the admin
      catalog to every visitor who never sees the admin.
    * `index.ts` — `locales`, `domains`, `Locale`/`Domain`/`TranslationKey`
      types, `loadCatalog(locale, domains?)` (dynamic imports, one per
      chunk), and `createT` with `%{var}` interpolation and an overrides
      layer for runtime-edited translations.
    * `react.tsx` — provider + `useT(domain?)` hook (unless `react: false`).
      The provider takes a `domains` prop (which chunks to load) and an
      optional `initialCatalog` so a server-rendered route tree is already
      translated before hydration.

  The source locale gets no files. Its catalog is identity by construction —
  msgid IS the copy — and `createT` already falls back to the msgid, so
  writing it out is handing the copy back to itself in a file the browser
  then has to download. A source locale with real PO files on disk is read
  and emitted like any other.

  Files are only written when content changed, so `--check` in CI is cheap.
  Stale files under `catalog/` are removed (and reported by `--check`): the
  directory is generated output, and a renamed domain must not leave a
  catalog behind that still type-checks.
  """
  use Mix.Task

  @shortdoc "Generate TypeScript catalogs from PO files"

  alias GettextTs.{Catalog, Config}

  @impl Mix.Task
  def run(args) do
    {opts, _, _} = OptionParser.parse(args, switches: [check: :boolean])

    data = Catalog.read(Config.gettext_path(), include_source: false)
    pot = Catalog.pot_index()
    out = Path.expand(Config.output_path(), File.cwd!())

    files =
      for {locale, by_domain} <- data,
          {domain, entries} <- by_domain,
          into: %{} do
        {Path.join([out, "catalog", locale, "#{domain}.ts"]), domain_ts(locale, domain, entries)}
      end

    files = Map.put(files, Path.join(out, "index.ts"), index_ts(data, pot))

    files =
      if Config.react?(),
        do: Map.put(files, Path.join(out, "react.tsx"), react_tsx()),
        else: files

    unless opts[:check], do: Enum.each(files, fn {p, _} -> File.mkdir_p!(Path.dirname(p)) end)

    changed =
      for {path, content} <- files, File.read(path) != {:ok, content} do
        unless opts[:check], do: File.write!(path, content)
        Path.relative_to_cwd(path)
      end

    stale =
      for path <- Path.wildcard(Path.join([out, "catalog", "**", "*.ts"])),
          not Map.has_key?(files, path) do
        unless opts[:check], do: File.rm!(path)
        Path.relative_to_cwd(path)
      end

    unless opts[:check], do: prune_empty_dirs(Path.join(out, "catalog"))

    report(changed ++ stale, opts)
  end

  defp report([], _opts), do: :ok

  defp report(changed, opts) do
    if opts[:check] do
      Mix.raise("gettext_ts.codegen --check: stale files: #{Enum.join(changed, ", ")}")
    else
      Mix.shell().info(
        "gettext_ts: wrote #{length(changed)} file(s) under #{Config.output_path()}"
      )
    end
  end

  defp prune_empty_dirs(root) do
    for dir <- Path.wildcard(Path.join(root, "*")), File.dir?(dir), File.ls!(dir) == [] do
      File.rmdir!(dir)
    end
  end

  defp domain_ts(locale, domain, entries) do
    lines =
      entries
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map_join(",\n", fn {id, str} -> "  #{ts_str(id)}: #{ts_str(str)}" end)

    body = if lines == "", do: "", else: "\n#{lines},\n"

    """
    // AUTO-GENERATED by mix gettext_ts.codegen — DO NOT EDIT
    // Locale: #{locale} · domain: #{domain}. Source: #{Config.gettext_path()}.
    const catalog: Record<string, string> = {#{body}};

    export default catalog;
    """
  end

  defp index_ts(data, pot) do
    locales =
      data |> Map.keys() |> Kernel.++([Config.source_locale()]) |> Enum.uniq() |> Enum.sort()

    domains = pot |> Map.keys() |> Enum.sort()
    default_domain = Config.default_domain()

    key_union =
      pot
      |> Enum.flat_map(fn {_d, ids} -> ids end)
      |> Enum.uniq()
      |> Enum.sort()
      |> case do
        [] -> "never"
        ids -> Enum.map_join(ids, "\n  | ", &ts_str/1)
      end

    """
    // AUTO-GENERATED by mix gettext_ts.codegen — DO NOT EDIT
    export const locales = [#{Enum.map_join(locales, ", ", &ts_str/1)}] as const;
    export const domains = [#{Enum.map_join(domains, ", ", &ts_str/1)}] as const;
    export type Locale = (typeof locales)[number];
    export type Domain = (typeof domains)[number];
    export type TranslationKey =
      | #{key_union};

    export type DomainCatalog = Record<string, string>;
    /**
     * A locale's catalog, domain by domain. PARTIAL on purpose: a route tree
     * loads the domains it renders and nothing else, so a missing domain is
     * the normal case, not an error. Lookups in a domain that was not loaded
     * fall through to the msgid, which is the source language.
     */
    export type LocaleCatalog = Partial<Record<Domain, DomainCatalog>>;
    /** Runtime-edited translations layered over the compiled catalog. */
    export type Overrides = Partial<Record<Domain, DomainCatalog>>;

    type ChunkLoader = () => Promise<{ default: DomainCatalog }>;

    /**
     * One dynamic import per locale/domain pair. Written out rather than
     * built from a template string because bundlers resolve `import()` at
     * build time: a computed specifier produces either a bundling error or
     * one fat chunk holding every locale.
     */
    const chunks: Partial<Record<Locale, Partial<Record<Domain, ChunkLoader>>>> = {
    #{chunk_map(data)}};

    /**
     * Loads a locale's catalog. `only` restricts it to the named domains —
     * the whole point of per-domain chunks — and omitting it loads all of
     * them. Domains without a chunk (an untranslated locale, or the source
     * locale, which needs none) resolve to nothing and fall through to the
     * msgid.
     */
    export async function loadCatalog(
      locale: string,
      only?: readonly Domain[]
    ): Promise<LocaleCatalog> {
      const byDomain = chunks[locale as Locale];
      if (!byDomain) return {};
      const out: LocaleCatalog = {};
      await Promise.all(
        (only ?? domains)
          .filter((d) => byDomain[d] !== undefined)
          .map(async (d) => {
            out[d] = (await byDomain[d]!()).default;
          })
      );
      return out;
    }

    export type TFunction = (
      key: TranslationKey | (string & {}),
      vars?: Record<string, string | number>
    ) => string;

    function interpolate(s: string, vars?: Record<string, string | number>): string {
      if (!vars) return s;
      let out = s;
      for (const [k, v] of Object.entries(vars)) out = out.replaceAll(`%{${k}}`, String(v));
      return out;
    }

    /**
     * Translation function for one domain. Lookup order: overrides →
     * compiled catalog → the key itself (source-language passthrough, so
     * new strings render before codegen ran).
     */
    export function createT(
      catalog: LocaleCatalog | null,
      domain: Domain = #{ts_str(default_domain)},
      overrides?: Overrides
    ): TFunction {
      return (key, vars) =>
        interpolate(
          overrides?.[domain]?.[key] ?? catalog?.[domain]?.[key] ?? key,
          vars
        );
    }
    """
  end

  defp chunk_map(data) do
    data
    |> Enum.sort_by(&elem(&1, 0))
    |> Enum.map_join("", fn {locale, by_domain} ->
      loaders =
        by_domain
        |> Enum.sort_by(&elem(&1, 0))
        |> Enum.map_join("\n", fn {domain, _} ->
          "    #{ts_str(domain)}: () => import(#{ts_str("./catalog/#{locale}/#{domain}")}),"
        end)

      "  #{ts_str(locale)}: {\n#{loaders}\n  },\n"
    end)
  end

  defp react_tsx do
    default_domain = Config.default_domain()

    """
    // AUTO-GENERATED by mix gettext_ts.codegen — DO NOT EDIT
    "use client";

    import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
    import { createT, loadCatalog, type Domain, type LocaleCatalog, type Overrides, type TFunction } from "./index";

    const Ctx = createContext<{ catalog: LocaleCatalog | null; overrides?: Overrides }>({ catalog: null });

    /** Locale-aware translation hook. Renders source-language keys until a catalog is present. */
    export function useT(domain: Domain = #{inspect(default_domain)}): TFunction {
      const { catalog, overrides } = useContext(Ctx);
      return useMemo(() => createT(catalog, domain, overrides), [catalog, domain, overrides]);
    }

    /**
     * Loads the locale's catalog lazily. `overrides` carries runtime-edited
     * translations (e.g. admin-changed copy fetched from the backend) and is
     * layered over the compiled catalog.
     *
     * `domains` picks the chunks to load. Omit it and the whole locale
     * arrives; name them and a route tree pays only for the copy it renders.
     * Nest a second provider (with its own `domains`) around a subtree that
     * needs more — an admin area inside a public site is the case this
     * exists for.
     *
     * `initialCatalog` seeds the FIRST render, server included. Without it the
     * catalog is null until the effect resolves, so a server-rendered page in a
     * non-source locale ships source-language HTML and swaps after hydration —
     * invisible to crawlers and a visible flash to everyone else. Import the
     * domains' chunks statically and pass them here for a per-locale route
     * tree; the lazy load still runs and refreshes the state afterwards.
     */
    export function I18nProvider({ locale, domains, overrides, initialCatalog, children }: {
      locale: string; domains?: readonly Domain[]; overrides?: Overrides; initialCatalog?: LocaleCatalog; children: ReactNode;
    }) {
      const [catalog, setCatalog] = useState<LocaleCatalog | null>(initialCatalog ?? null);

      // `domains` is almost always a fresh array literal, and a fresh array is
      // a new dependency every render — the effect would reload the catalog
      // forever. Serializing gives the value identity the array lacks, and
      // keeps `[]` (load nothing) distinct from undefined (load everything).
      const domainKey = JSON.stringify(domains ?? null);

      useEffect(() => {
        let cancelled = false;
        const only = (JSON.parse(domainKey) as Domain[] | null) ?? undefined;
        loadCatalog(locale, only).then((c) => { if (!cancelled) setCatalog(c); });
        return () => { cancelled = true; };
      }, [locale, domainKey]);

      const value = useMemo(() => ({ catalog, overrides }), [catalog, overrides]);
      return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
    }
    """
  end

  defp ts_str(s) do
    escaped =
      s
      |> String.replace("\\", "\\\\")
      |> String.replace("\"", "\\\"")
      |> String.replace("\n", "\\n")

    "\"#{escaped}\""
  end
end
